name: Cypress with Cucumber tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 20]
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set execute permissions for Cypress
      run: chmod +x node_modules/.bin/cypress

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
        wait-on: 'https://automationexercise.com/'
        wait-on-timeout: 120
        runTests: npm run cy:run